/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.Observation;
import java.util.ArrayList;

/**
 *
 * @author tanujkodali
 */
public class AssignJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignJPanel
     */
       private Application application;
    public AssignJPanel() {
        initComponents();
    }

     public AssignJPanel(Application application) {
        initComponents();
        
        this.application= application;
        
        populateComboBox();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      public void populateComboBox(){
        ArrayList<Medicine> meds = this.application.getCatalog().getMedicineCatalog();
        ArrayList<Observation> obs = this.application.getHistory().getVitalSignHHistory();
        
        for(Observation o: obs){
            oComboBox.addItem(o);
        }
        
        for(Medicine m: meds){
            medicineComboBox.addItem(m);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicineComboBox = new javax.swing.JComboBox();
        oComboBox = new javax.swing.JComboBox();
        assignMedicineBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        oComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                oComboBoxItemStateChanged(evt);
            }
        });

        assignMedicineBtn.setText("ASSIGN");
        assignMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMedicineBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(medicineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(oComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(assignMedicineBtn)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 80, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(medicineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(83, 83, 83)
                    .addComponent(assignMedicineBtn)
                    .addGap(0, 81, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_oComboBoxItemStateChanged
        // TODO add your handling code here:

        Observation o = (Observation) oComboBox.getSelectedItem();

        if(o.getMedication() != null){
            jLabel1.setText(o.getMedication().getMedicineName());
        }
    }//GEN-LAST:event_oComboBoxItemStateChanged

    private void assignMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMedicineBtnActionPerformed
        // TODO add your handling code here:

        //assign selected med to obs

        Observation o = (Observation) oComboBox.getSelectedItem();
        Medicine m = (Medicine) medicineComboBox.getSelectedItem();
        o.setMedication(m);
    }//GEN-LAST:event_assignMedicineBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignMedicineBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox medicineComboBox;
    private javax.swing.JComboBox oComboBox;
    // End of variables declaration//GEN-END:variables

   
}
