/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.MedicineCatalog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanujkodali
 */
public class CatalogJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CatalogJpanel
     */
       private Application application;
    DefaultTableModel medTableModel;
    Medicine selectedMed;
    public CatalogJpanel() {
        initComponents();
    }
     CatalogJpanel(Application application) {
        initComponents();
        
        this.application= application;
        this.medTableModel = (DefaultTableModel) mediceneCatTable.getModel();
        
        dispMedCatalog();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cfieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cfieldDosage = new javax.swing.JTextField();
        additionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mediceneCatTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Create a Vital Sign");

        jLabel2.setText("Name:");

        cfieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cfieldNameFocusLost(evt);
            }
        });

        jLabel3.setText("Dosage:");

        additionButton.setText("ADD");
        additionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionButtonActionPerformed(evt);
            }
        });

        mediceneCatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Dosage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mediceneCatTable);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(cfieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(cfieldDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(additionButton)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(510, 510, 510)
                            .addComponent(deleteButton)))
                    .addGap(0, 190, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(jLabel2)
                            .addGap(24, 24, 24)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(74, 74, 74)
                            .addComponent(cfieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(cfieldDosage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(additionButton)))
                    .addGap(213, 213, 213)
                    .addComponent(deleteButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cfieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cfieldNameFocusLost
        // TODO add your handling code here:

        String name = cfieldName.getText();
        Boolean isUnique = this.application.getCatalog().checkIfMedicineUnique(name);
        if(isUnique){

        } else{
            cfieldName.setText("");
            JOptionPane.showMessageDialog(null,"Medicine exits!");
        }
    }//GEN-LAST:event_cfieldNameFocusLost

    private void additionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionButtonActionPerformed
        // TODO add your handling code here:

        String name = cfieldName.getText();
        String dosage  = cfieldDosage.getText();

        MedicineCatalog catalog = this.application.getCatalog();
        catalog.createMedicine(name, Double.valueOf(dosage));

        dispMedCatalog();
    }//GEN-LAST:event_additionButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow  =  mediceneCatTable.getSelectedRow();

        if(selectedRow >= 0){
            //delete the object
            this.selectedMed = (Medicine) mediceneCatTable.getValueAt(selectedRow,0);
            this.application.getCatalog().deleteMedicine(selectedMed.getMedicineName());

            dispMedCatalog();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    public void dispMedCatalog(){
        //check if catalog is not empty
        
        ArrayList<Medicine> meds = this.application.getCatalog().getMedicineCatalog();
        
        if(meds.size() > 0){
            //populate the table
            
            medTableModel.setRowCount(0);
            
            for(Medicine m : meds){
                //row1 obj 
                
                Object row[] = new Object[2];
                row[0] = m;
                row[1] = m.getDosage();
                
                medTableModel.addRow(row);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additionButton;
    private javax.swing.JTextField cfieldDosage;
    private javax.swing.JTextField cfieldName;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mediceneCatTable;
    // End of variables declaration//GEN-END:variables
}
