/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import model.Address;
import model.Person;
import model.contact;


/**
 *
 * @author tanujkodali
 */
public class MyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyJFrame
     */
    
    private Person person;

    
    
    public MyJFrame() {
        initComponents();
        
        this.person= new Person();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        DetailsLayout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldnuid = new javax.swing.JTextField();
        fieldfirstname = new javax.swing.JTextField();
        fieldlastname = new javax.swing.JTextField();
        fieldcollegename = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldoffphone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldoffemailid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fieldpersonalphone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldpersonalemailid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fieldcurrentstreetname = new javax.swing.JTextField();
        fieldcurrentaptno = new javax.swing.JTextField();
        fieldcurrentcity = new javax.swing.JTextField();
        fieldcurrentzipcode = new javax.swing.JTextField();
        fieldpermanentstreetname = new javax.swing.JTextField();
        fieldpermanentaptno = new javax.swing.JTextField();
        fieldpermanentcity = new javax.swing.JTextField();
        fieldpermanentzipcode = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        DisplayDetails = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        viewnuid = new javax.swing.JLabel();
        viewfirstname = new javax.swing.JLabel();
        viewlastname = new javax.swing.JLabel();
        viewcollegename = new javax.swing.JLabel();
        viewofficephone = new javax.swing.JLabel();
        viewofficeemailid = new javax.swing.JLabel();
        viewpersonalphone = new javax.swing.JLabel();
        viewpersonalemailid = new javax.swing.JLabel();
        viewcurrentstreet = new javax.swing.JLabel();
        viewcurrentapt = new javax.swing.JLabel();
        viewcurrentcity = new javax.swing.JLabel();
        viewcurrentzip = new javax.swing.JLabel();
        viewperstreet = new javax.swing.JLabel();
        viewperapt = new javax.swing.JLabel();
        viewpercity = new javax.swing.JLabel();
        viewperzip = new javax.swing.JLabel();

        jTextField5.setText("jTextField5");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel22.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DetailsLayout.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("NUID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("College Name");

        jLabel5.setText("Contact-Office");

        fieldnuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldnuidActionPerformed(evt);
            }
        });

        jLabel7.setText("Phone");

        jLabel8.setText("Emial-Id");

        jLabel9.setText("Contact-Personal");

        jLabel10.setText("Phone");

        fieldpersonalphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpersonalphoneActionPerformed(evt);
            }
        });

        jLabel11.setText("Email-Id");

        jLabel12.setText("Current Address");

        jLabel13.setText("Street Name");

        jLabel14.setText("Apt. No");

        jLabel15.setText("City/State");

        jLabel16.setText("ZipCode");

        jLabel17.setText("Permanent Address");

        jLabel18.setText("Street Name");

        jLabel19.setText("Apt.No");

        jLabel20.setText("City/State");

        jLabel21.setText("ZipCode");

        fieldpermanentstreetname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpermanentstreetnameActionPerformed(evt);
            }
        });

        fieldpermanentzipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpermanentzipcodeActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DetailsLayoutLayout = new javax.swing.GroupLayout(DetailsLayout);
        DetailsLayout.setLayout(DetailsLayoutLayout);
        DetailsLayoutLayout.setHorizontalGroup(
            DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsLayoutLayout.createSequentialGroup()
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DetailsLayoutLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldpersonalemailid))
                    .addGroup(DetailsLayoutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldcurrentstreetname)
                            .addComponent(fieldcurrentaptno)
                            .addComponent(fieldcurrentcity)
                            .addComponent(fieldcurrentzipcode)))
                    .addGroup(DetailsLayoutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DetailsLayoutLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldcollegename))
                            .addGroup(DetailsLayoutLayout.createSequentialGroup()
                                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldnuid)
                                    .addComponent(fieldfirstname)
                                    .addComponent(fieldlastname)))
                            .addGroup(DetailsLayoutLayout.createSequentialGroup()
                                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(DetailsLayoutLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldoffphone))
                            .addGroup(DetailsLayoutLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldoffemailid)
                                    .addComponent(fieldpersonalphone, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                            .addComponent(jLabel9)))
                    .addGroup(DetailsLayoutLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DetailsLayoutLayout.createSequentialGroup()
                                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldpermanentstreetname)
                                    .addComponent(fieldpermanentaptno, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                            .addGroup(DetailsLayoutLayout.createSequentialGroup()
                                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldpermanentcity)
                                    .addComponent(fieldpermanentzipcode))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsLayoutLayout.createSequentialGroup()
                .addGap(0, 138, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addGap(109, 109, 109))
        );
        DetailsLayoutLayout.setVerticalGroup(
            DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsLayoutLayout.createSequentialGroup()
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsLayoutLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(fieldnuid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fieldfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fieldlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DetailsLayoutLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldcollegename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsLayoutLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6))
                    .addGroup(DetailsLayoutLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldoffphone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(16, 16, 16)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldoffemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldpersonalphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldpersonalemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(36, 36, 36)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(fieldcurrentstreetname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(fieldcurrentaptno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(fieldcurrentcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(fieldcurrentzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18)
                    .addComponent(fieldpermanentstreetname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(fieldpermanentaptno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(fieldpermanentcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(DetailsLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsLayoutLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(fieldpermanentzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(saveBtn)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(DetailsLayout);

        DisplayDetails.setBackground(new java.awt.Color(153, 153, 153));

        jLabel23.setText("NUID");

        jLabel24.setText("FirstName");

        jLabel25.setText("LastName");

        jLabel26.setText("CollegeName");

        jLabel27.setText("Contact Office");

        jLabel28.setText("Phone");

        jLabel29.setText("Email Id");

        jLabel30.setText("Contact  Personal");

        jLabel31.setText("Phone");

        jLabel32.setText("Email Id");

        jLabel33.setText("Current Address");

        jLabel34.setText("Street Name ");

        jLabel35.setText("Apt. No");

        jLabel36.setText("City/State");

        jLabel37.setText("ZipCode");

        jLabel38.setText("Permanent Address");

        jLabel39.setText("Street Name");

        jLabel40.setText("Apt. No");

        jLabel41.setText("City/State");

        jLabel42.setText("ZipCode");

        javax.swing.GroupLayout DisplayDetailsLayout = new javax.swing.GroupLayout(DisplayDetails);
        DisplayDetails.setLayout(DisplayDetailsLayout);
        DisplayDetailsLayout.setHorizontalGroup(
            DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayDetailsLayout.createSequentialGroup()
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(DisplayDetailsLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel31)
                                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28))
                                .addComponent(jLabel32)
                                .addComponent(jLabel34)
                                .addComponent(jLabel35)
                                .addComponent(jLabel36)
                                .addComponent(jLabel37)
                                .addComponent(jLabel39)
                                .addComponent(jLabel40)
                                .addComponent(jLabel41)
                                .addComponent(jLabel42))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(viewofficephone, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewofficeemailid, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewpersonalphone, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewpersonalemailid, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewcurrentstreet, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewcurrentapt, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewcurrentcity, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewcurrentzip, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewperstreet, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewperapt, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewpercity, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewperzip, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(DisplayDetailsLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(200, 200, 200)
                            .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(viewnuid)
                                .addComponent(viewfirstname)
                                .addComponent(viewlastname)
                                .addComponent(viewcollegename))))
                    .addGroup(DisplayDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel33)
                            .addComponent(jLabel38))))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        DisplayDetailsLayout.setVerticalGroup(
            DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(viewnuid))
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(viewfirstname))
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewlastname))
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(viewcollegename))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(viewofficephone))
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(viewofficeemailid))
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(viewpersonalphone))
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(viewpersonalemailid))
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(viewcurrentstreet))
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(viewcurrentapt))
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayDetailsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36))
                    .addGroup(DisplayDetailsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(viewcurrentcity)))
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(viewcurrentzip))
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(viewperstreet))
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(viewperapt))
                .addGap(18, 18, 18)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(viewpercity))
                .addGap(27, 27, 27)
                .addGroup(DisplayDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(viewperzip))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(DisplayDetails);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void fieldnuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldnuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldnuidActionPerformed

    private void fieldpersonalphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpersonalphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldpersonalphoneActionPerformed

    private void fieldpermanentstreetnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpermanentstreetnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldpermanentstreetnameActionPerformed

    private void fieldpermanentzipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpermanentzipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldpermanentzipcodeActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        long nuid = Long.valueOf(fieldnuid.getText());
        String firstname= fieldfirstname.getText();
        String lastname= fieldlastname.getText();
        String collegename= fieldcollegename.getText();
        
        long officephone = Long.valueOf(fieldoffphone.getText());
        String officeemail = fieldoffemailid.getText();
        
        long personalphone = Long.valueOf(fieldpersonalphone.getText());
        String personalemail = fieldpersonalemailid.getText();

        String currentstreet = fieldcurrentstreetname.getText();
        String currentaptno = fieldcurrentaptno.getText();
        String currentcity = fieldcurrentcity.getText();
        long currentzipcode = Long.valueOf(fieldcurrentzipcode.getText());
        
        String permanentstreet = fieldpermanentstreetname.getText();
        String permanentaptno = fieldpermanentaptno.getText();
        String permanentcity = fieldpermanentcity.getText();
        long permanentzipcode = Long.valueOf(fieldpermanentzipcode.getText());
        
        
        
        this.person.setNUID(nuid);
        this.person.setFirstname(firstname);
        this.person.setLastname(lastname);
        this.person.setCollegename(collegename);
        
        contact officecontact = this.person.getOfficephone();
        officecontact.setPhone(officephone);
        officecontact.setEmailId(officeemail);
        
        contact personalcontact = this.person.getPermanentphone();
        personalcontact.setPhone(personalphone);
        personalcontact.setEmailId(personalemail);
        
        Address currentaddress = this.person.getOfficeaddress();
        currentaddress.setStreet(currentstreet);
        currentaddress.setAptNo(currentaptno);
        currentaddress.setCity(currentcity);
        currentaddress.setZipcode(currentzipcode);
        
        Address permanentaddress = this.person.getPermanentaddress();
        permanentaddress.setStreet(permanentstreet);
        permanentaddress.setAptNo(permanentaptno);
        permanentaddress.setCity(currentcity);
        permanentaddress.setZipcode(permanentzipcode);
        
        display();
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void display(){
        
        viewnuid.setText(String.valueOf(this.person.getNUID()));
        viewfirstname.setText(this.person.getFirstname());
        viewlastname.setText(this.person.getLastname());
        viewcollegename.setText(this.person.getCollegename());
        
        viewofficephone.setText(String.valueOf(this.person.getOfficephone().getPhone()));
        viewofficeemailid.setText(this.person.getOfficephone().getEmailId());
 
        viewpersonalphone.setText(String.valueOf(this.person.getPermanentphone().getPhone()));
        viewpersonalemailid.setText(this.person.getPermanentphone().getEmailId());
        
        viewcurrentstreet.setText(this.person.getOfficeaddress().getStreet());
        viewcurrentapt.setText(this.person.getOfficeaddress().getAptNo());
        viewcurrentcity.setText(this.person.getOfficeaddress().getCity());
        viewcurrentzip.setText(String.valueOf(this.person.getOfficeaddress().getZipcode()));
        
        viewperstreet.setText(this.person.getPermanentaddress().getStreet());
        viewperapt.setText(this.person.getPermanentaddress().getAptNo());
        viewpercity.setText(this.person.getPermanentaddress().getCity());
        viewperzip.setText(String.valueOf(this.person.getPermanentaddress().getZipcode()));
           
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailsLayout;
    private javax.swing.JPanel DisplayDetails;
    private javax.swing.JTextField fieldcollegename;
    private javax.swing.JTextField fieldcurrentaptno;
    private javax.swing.JTextField fieldcurrentcity;
    private javax.swing.JTextField fieldcurrentstreetname;
    private javax.swing.JTextField fieldcurrentzipcode;
    private javax.swing.JTextField fieldfirstname;
    private javax.swing.JTextField fieldlastname;
    private javax.swing.JTextField fieldnuid;
    private javax.swing.JTextField fieldoffemailid;
    private javax.swing.JTextField fieldoffphone;
    private javax.swing.JTextField fieldpermanentaptno;
    private javax.swing.JTextField fieldpermanentcity;
    private javax.swing.JTextField fieldpermanentstreetname;
    private javax.swing.JTextField fieldpermanentzipcode;
    private javax.swing.JTextField fieldpersonalemailid;
    private javax.swing.JTextField fieldpersonalphone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel viewcollegename;
    private javax.swing.JLabel viewcurrentapt;
    private javax.swing.JLabel viewcurrentcity;
    private javax.swing.JLabel viewcurrentstreet;
    private javax.swing.JLabel viewcurrentzip;
    private javax.swing.JLabel viewfirstname;
    private javax.swing.JLabel viewlastname;
    private javax.swing.JLabel viewnuid;
    private javax.swing.JLabel viewofficeemailid;
    private javax.swing.JLabel viewofficephone;
    private javax.swing.JLabel viewperapt;
    private javax.swing.JLabel viewpercity;
    private javax.swing.JLabel viewpersonalemailid;
    private javax.swing.JLabel viewpersonalphone;
    private javax.swing.JLabel viewperstreet;
    private javax.swing.JLabel viewperzip;
    // End of variables declaration//GEN-END:variables
}
